#!/usr/bin/env bash
set -euo pipefail

# ─── setup.sh ────────────────────────────────────────────────────────────────
# One-time setup: generates a .env file with random secrets.
# Run once, then: docker compose up
# ─────────────────────────────────────────────────────────────────────────────

if [ -f .env ]; then
  echo ""
  echo "⚠️  .env already exists."
  echo "   Delete it first if you want to regenerate secrets:"
  echo "   rm .env && ./setup.sh"
  echo ""
  exit 1
fi

if ! command -v openssl &> /dev/null; then
  echo "❌  openssl is required but not found. Install it and try again."
  exit 1
fi

AUTH_SECRET=$(openssl rand -base64 32)
DB_PASS=$(openssl rand -hex 16)
STORAGE_PASS=$(openssl rand -hex 16)

cat > .env <<EOF
# ─── Reqcore — generated by setup.sh ───────────────────────────────────────
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ❗ Do NOT commit this file. See .env.example for production variable reference.

# ─── Database ────────────────────────────────────────────────────────────────
DB_USER=reqcore
DB_PASSWORD=${DB_PASS}
DB_NAME=reqcore

# Used by host tools (drizzle-kit, drizzle studio). docker-compose overrides
# this with the internal Docker hostname for the app container.
DATABASE_URL=postgresql://reqcore:${DB_PASS}@localhost:5432/reqcore

# ─── Authentication ──────────────────────────────────────────────────────────
BETTER_AUTH_SECRET=${AUTH_SECRET}
BETTER_AUTH_URL=http://localhost:3000
FACTORY_DISABLE_PUBLIC_SIGNUP=false
FACTORY_ADMIN_SSO_ONLY=false
FACTORY_DISABLE_PUBLIC_ORG_CREATION=false

# ─── Object Storage ──────────────────────────────────────────────────────────
STORAGE_USER=reqcore
STORAGE_PASSWORD=${STORAGE_PASS}

# Used by host tools. docker-compose overrides this for the app container.
S3_ENDPOINT=http://localhost:9000
S3_ACCESS_KEY=reqcore
S3_SECRET_KEY=${STORAGE_PASS}
S3_BUCKET=reqcore
S3_REGION=us-east-1
S3_FORCE_PATH_STYLE=true

# ─── SEO ─────────────────────────────────────────────────────────────────────
NUXT_PUBLIC_SITE_URL=http://localhost:3000
EOF

echo ""
echo "✅  .env generated with random secrets."
echo ""
echo "Start the stack:"
echo "  docker compose up"
echo ""
echo "App → http://localhost:3000"
echo ""
echo "Optional — seed demo account (after the app is running):"
echo "  docker compose exec app npm run db:seed"
echo "  Login: demo@thefactoryhq.com / demo1234"
echo ""
