export type CliRouteCoverageEntry =
  | {
      route: string
      status: 'supported'
      command: string
      reason?: never
    }
  | {
      route: string
      status: 'excluded' | 'internal' | 'intentionally-public'
      reason: string
      command?: never
    }

export const cliRouteCoverage: CliRouteCoverageEntry[] = [
  { route: 'server/api/activity-log/candidate-timeline.get.ts', status: 'supported', command: 'dashboard candidate-timeline' },
  { route: 'server/api/activity-log/index.get.ts', status: 'supported', command: 'dashboard activity' },
  { route: 'server/api/activity-log/timeline.get.ts', status: 'supported', command: 'dashboard timeline' },
  { route: 'server/api/ai-analysis/stats.get.ts', status: 'supported', command: 'dashboard ai-stats' },
  { route: 'server/api/ai-config/[id].delete.ts', status: 'supported', command: 'ai-config delete' },
  { route: 'server/api/ai-config/[id].get.ts', status: 'supported', command: 'ai-config get' },
  { route: 'server/api/ai-config/[id].patch.ts', status: 'supported', command: 'ai-config update' },
  { route: 'server/api/ai-config/[id]/set-default.post.ts', status: 'supported', command: 'ai-config set-default' },
  { route: 'server/api/ai-config/[id]/test-connection.post.ts', status: 'supported', command: 'ai-config test-connection' },
  { route: 'server/api/ai-config/generate-criteria.post.ts', status: 'supported', command: 'ai-config generate-criteria' },
  { route: 'server/api/ai-config/index.get.ts', status: 'supported', command: 'ai-config list' },
  { route: 'server/api/ai-config/index.post.ts', status: 'supported', command: 'ai-config create' },
  { route: 'server/api/ai-config/providers.get.ts', status: 'supported', command: 'ai-config providers' },
  { route: 'server/api/ai-config/providers/refresh.post.ts', status: 'supported', command: 'ai-config refresh-providers' },
  { route: 'server/api/applications/[id].get.ts', status: 'supported', command: 'applications get' },
  { route: 'server/api/applications/[id].patch.ts', status: 'supported', command: 'applications update' },
  { route: 'server/api/applications/[id]/analyze.post.ts', status: 'supported', command: 'applications analyze' },
  { route: 'server/api/applications/[id]/properties/[propId].put.ts', status: 'supported', command: 'applications set-property' },
  { route: 'server/api/applications/[id]/scores.get.ts', status: 'supported', command: 'applications scores' },
  { route: 'server/api/applications/[id]/scoring-feedback.post.ts', status: 'excluded', reason: 'Dashboard-only qualitative feedback on an AI analysis run; CLI parity will wait until scoring review workflows are productized.' },
  { route: 'server/api/applications/analyze-missing.post.ts', status: 'supported', command: 'applications analyze-missing' },
  { route: 'server/api/applications/index.get.ts', status: 'supported', command: 'applications list' },
  { route: 'server/api/applications/index.post.ts', status: 'supported', command: 'applications create' },
  { route: 'server/api/auth/[...all].ts', status: 'internal', reason: 'Better Auth catch-all endpoint; CLI uses supported auth commands and bearer/device auth through this boundary.' },
  { route: 'server/api/auth/demo-check.get.ts', status: 'internal', reason: 'Demo-only auth helper, not a supported automation API.' },
  { route: 'server/api/auth/demo-fresh-signup.get.ts', status: 'internal', reason: 'Demo-only auth helper, not a supported automation API.' },
  { route: 'server/api/auth/factory-sso.get.ts', status: 'internal', reason: 'Browser-only Microsoft SSO launcher that sets OAuth state before redirecting to the identity provider; CLI uses device authorization.' },
  { route: 'server/api/auth/providers.get.ts', status: 'internal', reason: 'Browser sign-in provider metadata used by the web UI, not a deterministic CLI workflow.' },
  { route: 'server/api/calendar/disconnect.post.ts', status: 'supported', command: 'calendar disconnect' },
  { route: 'server/api/calendar/google/callback.get.ts', status: 'internal', reason: 'OAuth provider callback handled by the browser/provider flow.' },
  { route: 'server/api/calendar/google/connect.get.ts', status: 'supported', command: 'calendar connect' },
  { route: 'server/api/calendar/microsoft/callback.get.ts', status: 'internal', reason: 'OAuth provider callback handled by the browser/provider flow.' },
  { route: 'server/api/calendar/microsoft/connect.get.ts', status: 'supported', command: 'calendar connect' },
  { route: 'server/api/calendar/renew-webhooks.post.ts', status: 'supported', command: 'calendar renew-webhooks' },
  { route: 'server/api/calendar/status.get.ts', status: 'supported', command: 'calendar status' },
  { route: 'server/api/calendar/webhook.post.ts', status: 'internal', reason: 'Provider webhook receiver, not a user or agent command.' },
  { route: 'server/api/candidates/[id].delete.ts', status: 'supported', command: 'candidates delete' },
  { route: 'server/api/candidates/[id].get.ts', status: 'supported', command: 'candidates get' },
  { route: 'server/api/candidates/[id].patch.ts', status: 'supported', command: 'candidates update' },
  { route: 'server/api/candidates/[id]/documents/index.post.ts', status: 'supported', command: 'documents upload' },
  { route: 'server/api/candidates/[id]/properties/[propId].put.ts', status: 'supported', command: 'candidates set-property' },
  { route: 'server/api/candidates/index.get.ts', status: 'supported', command: 'candidates list' },
  { route: 'server/api/candidates/index.post.ts', status: 'supported', command: 'candidates create' },
  { route: 'server/api/chatbot/agents/[id].delete.ts', status: 'supported', command: 'chatbot agents delete' },
  { route: 'server/api/chatbot/agents/[id].patch.ts', status: 'supported', command: 'chatbot agents update' },
  { route: 'server/api/chatbot/agents/index.get.ts', status: 'supported', command: 'chatbot agents list' },
  { route: 'server/api/chatbot/agents/index.post.ts', status: 'supported', command: 'chatbot agents create' },
  { route: 'server/api/chatbot/chat.post.ts', status: 'supported', command: 'chatbot chat' },
  { route: 'server/api/chatbot/conversations/[id].delete.ts', status: 'supported', command: 'chatbot conversations delete' },
  { route: 'server/api/chatbot/conversations/[id].get.ts', status: 'supported', command: 'chatbot conversations get' },
  { route: 'server/api/chatbot/conversations/[id].patch.ts', status: 'supported', command: 'chatbot conversations update' },
  { route: 'server/api/chatbot/conversations/index.get.ts', status: 'supported', command: 'chatbot conversations list' },
  { route: 'server/api/chatbot/conversations/index.post.ts', status: 'supported', command: 'chatbot conversations create' },
  { route: 'server/api/chatbot/folders/[id].delete.ts', status: 'supported', command: 'chatbot folders delete' },
  { route: 'server/api/chatbot/folders/[id].patch.ts', status: 'supported', command: 'chatbot folders update' },
  { route: 'server/api/chatbot/folders/index.get.ts', status: 'supported', command: 'chatbot folders list' },
  { route: 'server/api/chatbot/folders/index.post.ts', status: 'supported', command: 'chatbot folders create' },
  { route: 'server/api/chatbot/upload.post.ts', status: 'supported', command: 'chatbot upload' },
  { route: 'server/api/cli/capabilities.get.ts', status: 'supported', command: 'system capabilities' },
  { route: 'server/api/comments/[id].delete.ts', status: 'supported', command: 'comments delete' },
  { route: 'server/api/comments/[id].patch.ts', status: 'supported', command: 'comments update' },
  { route: 'server/api/comments/index.get.ts', status: 'supported', command: 'comments list' },
  { route: 'server/api/comments/index.post.ts', status: 'supported', command: 'comments create' },
  { route: 'server/api/compliance/applications/summary.get.ts', status: 'excluded', reason: 'Dashboard-only privacy-protected aggregate compliance report; no CLI workflow until exports/reporting are productized.' },
  { route: 'server/api/dashboard/stats.get.ts', status: 'supported', command: 'dashboard summary' },
  { route: 'server/api/documents/[id].delete.ts', status: 'supported', command: 'documents delete' },
  { route: 'server/api/documents/[id]/download.get.ts', status: 'supported', command: 'documents download' },
  { route: 'server/api/documents/[id]/parse.post.ts', status: 'supported', command: 'documents parse' },
  { route: 'server/api/documents/[id]/preview.get.ts', status: 'supported', command: 'documents preview' },
  { route: 'server/api/documents/parse-all.post.ts', status: 'supported', command: 'documents parse-all' },
  { route: 'server/api/email-templates/[id]/index.delete.ts', status: 'supported', command: 'email-templates delete' },
  { route: 'server/api/email-templates/[id]/index.patch.ts', status: 'supported', command: 'email-templates update' },
  { route: 'server/api/email-templates/index.get.ts', status: 'supported', command: 'email-templates list' },
  { route: 'server/api/email-templates/index.post.ts', status: 'supported', command: 'email-templates create' },
  { route: 'server/api/feedback.post.ts', status: 'supported', command: 'feedback submit' },
  { route: 'server/api/feedback/config.get.ts', status: 'supported', command: 'feedback status' },
  { route: 'server/api/healthz.get.ts', status: 'internal', reason: 'Hosting health probe, not an authenticated ATS workflow.' },
  { route: 'server/api/interviews/[id]/index.delete.ts', status: 'supported', command: 'interviews cancel' },
  { route: 'server/api/interviews/[id]/index.get.ts', status: 'supported', command: 'interviews get' },
  { route: 'server/api/interviews/[id]/index.patch.ts', status: 'supported', command: 'interviews update' },
  { route: 'server/api/interviews/[id]/send-invitation.post.ts', status: 'supported', command: 'interviews send-invitation' },
  { route: 'server/api/interviews/index.get.ts', status: 'supported', command: 'interviews list' },
  { route: 'server/api/interviews/index.post.ts', status: 'supported', command: 'interviews schedule' },
  { route: 'server/api/invite-links/[id].delete.ts', status: 'supported', command: 'org invite-links revoke' },
  { route: 'server/api/invite-links/accept.post.ts', status: 'supported', command: 'org invite-links accept' },
  { route: 'server/api/invite-links/index.get.ts', status: 'supported', command: 'org invite-links list' },
  { route: 'server/api/invite-links/index.post.ts', status: 'supported', command: 'org invite-links create' },
  { route: 'server/api/invite-links/info/[token].get.ts', status: 'supported', command: 'org invite-links info' },
  { route: 'server/api/jobs/[id].delete.ts', status: 'supported', command: 'jobs delete' },
  { route: 'server/api/jobs/[id].get.ts', status: 'supported', command: 'jobs get' },
  { route: 'server/api/jobs/[id].patch.ts', status: 'supported', command: 'jobs update' },
  { route: 'server/api/jobs/[id]/analyze-all.post.ts', status: 'supported', command: 'jobs analyze-all' },
  { route: 'server/api/jobs/[id]/pipeline.get.ts', status: 'supported', command: 'jobs pipeline' },
  { route: 'server/api/jobs/[id]/criteria/generate.post.ts', status: 'supported', command: 'jobs criteria generate' },
  { route: 'server/api/jobs/[id]/criteria/index.get.ts', status: 'supported', command: 'jobs criteria list' },
  { route: 'server/api/jobs/[id]/criteria/index.patch.ts', status: 'supported', command: 'jobs criteria update-weights' },
  { route: 'server/api/jobs/[id]/criteria/index.post.ts', status: 'supported', command: 'jobs criteria replace' },
  { route: 'server/api/jobs/[id]/questions/[questionId].delete.ts', status: 'supported', command: 'jobs questions delete' },
  { route: 'server/api/jobs/[id]/questions/[questionId].patch.ts', status: 'supported', command: 'jobs questions update' },
  { route: 'server/api/jobs/[id]/questions/index.get.ts', status: 'supported', command: 'jobs questions list' },
  { route: 'server/api/jobs/[id]/questions/index.post.ts', status: 'supported', command: 'jobs questions create' },
  { route: 'server/api/jobs/[id]/questions/reorder.put.ts', status: 'supported', command: 'jobs questions reorder' },
  { route: 'server/api/jobs/index.get.ts', status: 'supported', command: 'jobs list' },
  { route: 'server/api/jobs/index.post.ts', status: 'supported', command: 'jobs create' },
  { route: 'server/api/join-requests/[id]/approve.post.ts', status: 'supported', command: 'org join-requests approve' },
  { route: 'server/api/join-requests/[id]/reject.post.ts', status: 'supported', command: 'org join-requests reject' },
  { route: 'server/api/join-requests/index.get.ts', status: 'supported', command: 'org join-requests list' },
  { route: 'server/api/join-requests/index.post.ts', status: 'supported', command: 'org join-requests create' },
  { route: 'server/api/org-search/index.get.ts', status: 'supported', command: 'org search' },
  { route: 'server/api/org-settings/index.get.ts', status: 'supported', command: 'org settings' },
  { route: 'server/api/org-settings/index.patch.ts', status: 'supported', command: 'org update-settings' },
  { route: 'server/api/properties/[id].delete.ts', status: 'supported', command: 'properties delete' },
  { route: 'server/api/properties/[id].patch.ts', status: 'supported', command: 'properties update' },
  { route: 'server/api/properties/index.get.ts', status: 'supported', command: 'properties list' },
  { route: 'server/api/properties/index.post.ts', status: 'supported', command: 'properties create' },
  { route: 'server/api/properties/reorder.post.ts', status: 'supported', command: 'properties reorder' },
  { route: 'server/api/privacy-requests/[id].get.ts', status: 'excluded', reason: 'Legal/privacy review workflow is intentionally constrained to the authenticated dashboard in v1.' },
  { route: 'server/api/privacy-requests/[id].patch.ts', status: 'excluded', reason: 'Legal/privacy review workflow is intentionally constrained to the authenticated dashboard in v1.' },
  { route: 'server/api/privacy-requests/[id]/fulfill.post.ts', status: 'excluded', reason: 'Destructive privacy fulfillment requires dashboard review and is not exposed to external agents.' },
  { route: 'server/api/privacy-requests/index.get.ts', status: 'excluded', reason: 'Legal/privacy review workflow is intentionally constrained to the authenticated dashboard in v1.' },
  { route: 'server/api/privacy-requests/index.post.ts', status: 'intentionally-public', reason: 'Applicant-facing privacy request intake form, not a staff/agent ATS command.' },
  { route: 'server/api/privacy-requests/verify.get.ts', status: 'intentionally-public', reason: 'Requester email verification link, not a staff/agent ATS command.' },
  { route: 'server/api/processing/[id].get.ts', status: 'supported', command: 'processing get' },
  { route: 'server/api/processing/[id]/drain.post.ts', status: 'supported', command: 'processing drain' },
  { route: 'server/api/public/interviews/respond.get.ts', status: 'intentionally-public', reason: 'Candidate-facing email-link response page, not a staff/agent ATS command.' },
  { route: 'server/api/public/interviews/respond.post.ts', status: 'intentionally-public', reason: 'Candidate-facing email-link response submission, not a staff/agent ATS command.' },
  { route: 'server/api/public/jobs/[slug].get.ts', status: 'supported', command: 'public jobs get' },
  { route: 'server/api/public/jobs/[slug]/apply.post.ts', status: 'supported', command: 'public jobs apply' },
  { route: 'server/api/public/jobs/index.get.ts', status: 'supported', command: 'public jobs list' },
  { route: 'server/api/public/track/[code].get.ts', status: 'intentionally-public', reason: 'Attribution redirect endpoint; CLI exposes reporting through source-tracking stats commands.' },
  { route: 'server/api/readyz.get.ts', status: 'internal', reason: 'Hosting readiness probe, not an authenticated ATS workflow.' },
  { route: 'server/api/source-tracking/stats.get.ts', status: 'supported', command: 'source-tracking stats' },
  { route: 'server/api/sso/providers.get.ts', status: 'supported', command: 'org sso-providers list' },
  { route: 'server/api/sso/providers.post.ts', status: 'supported', command: 'org sso-providers register' },
  { route: 'server/api/sso/providers/[id].delete.ts', status: 'supported', command: 'org sso-providers delete' },
  { route: 'server/api/tracking-links/[id].delete.ts', status: 'supported', command: 'source-tracking delete' },
  { route: 'server/api/tracking-links/[id].get.ts', status: 'supported', command: 'source-tracking get' },
  { route: 'server/api/tracking-links/[id].patch.ts', status: 'supported', command: 'source-tracking update' },
  { route: 'server/api/tracking-links/[id]/stats.get.ts', status: 'supported', command: 'source-tracking link-stats' },
  { route: 'server/api/tracking-links/index.get.ts', status: 'supported', command: 'source-tracking list' },
  { route: 'server/api/tracking-links/index.post.ts', status: 'supported', command: 'source-tracking create' },
  { route: 'server/api/updates/apply.post.ts', status: 'excluded', reason: 'Destructive maintenance operation; not exposed to external agents.' },
  { route: 'server/api/updates/backup.post.ts', status: 'excluded', reason: 'Destructive maintenance operation; not exposed to external agents.' },
  { route: 'server/api/updates/changelog.get.ts', status: 'supported', command: 'system changelog' },
  { route: 'server/api/updates/system.get.ts', status: 'supported', command: 'system info' },
  { route: 'server/api/updates/version.get.ts', status: 'supported', command: 'system version' },
]
