import { z } from "zod";

/**
 * Preprocessor that normalizes empty strings to undefined.
 * Some hosting platforms may set env vars to "" instead of leaving them unset.
 * This ensures `.default()` and `.optional()` work as expected.
 */
const emptyToUndefined = z.preprocess(
  (val) => (typeof val === "string" && val.trim() === "" ? undefined : val),
  z.string(),
);

const envFlag = (defaultValue: boolean) =>
  z.preprocess((val) => {
    if (typeof val === "string") {
      const trimmed = val.trim().toLowerCase();
      if (!trimmed) return defaultValue;
      return ["1", "true", "yes", "on"].includes(trimmed);
    }
    if (val === undefined) return defaultValue;
    return val;
  }, z.boolean().default(defaultValue));

const commaList = (defaultValue: string[] = []) =>
  z.preprocess(
    (val) => (typeof val === "string" && val.trim() === "" ? undefined : val),
    z.string().optional(),
  ).transform((value) =>
    value
      ? value
          .split(",")
          .map((item) => item.trim().toLowerCase())
          .filter(Boolean)
      : defaultValue,
  );

/**
 * Detect whether the current Railway environment is a PR/preview environment.
 * Production and long-lived environments must provide explicit BETTER_AUTH_URL.
 */
export function isRailwayPreviewEnvironment(environmentName?: string): boolean {
  const name = environmentName?.toLowerCase().trim() ?? "";

  if (!name) return false;

  // Never treat production as preview.
  if (name === "production" || name === "prod") return false;

  return (
    name.startsWith("pr") ||
    /^pr(?:-|\d)/.test(name) ||
    name.includes("pr-") ||
    name.includes("pr ") ||
    name.includes("pull request") ||
    name.includes("pull-request") ||
    name.includes("preview")
  );
}

/** @internal Exported for unit testing. */
export const envSchema = z
  .object({
    DATABASE_URL: z.url(),
    BETTER_AUTH_SECRET: emptyToUndefined.pipe(
      z.string().min(32, "BETTER_AUTH_SECRET must be at least 32 characters"),
    ),
    BETTER_AUTH_URL: z
      .preprocess((val) => {
        if (typeof val !== "string") return val;
        const trimmed = val.trim();
        // Treat empty strings and broken platform template refs ("https://") as unset
        if (trimmed === "" || trimmed === "https://" || trimmed === "http://")
          return undefined;
        return trimmed;
      }, z.string().url())
      .optional(),
    /** Comma-separated list of additional trusted origins for Better Auth CSRF checks. */
    BETTER_AUTH_TRUSTED_ORIGINS: emptyToUndefined
      .pipe(z.string())
      .transform((value) =>
        value
          .split(",")
          .map((origin) => origin.trim())
          .filter(Boolean),
      )
      .optional()
      .default([]),
    /** Railway environment metadata for PR/preview detection. */
    RAILWAY_ENVIRONMENT_NAME: emptyToUndefined.optional(),
    /** PR number provided by Railway for GitHub-triggered deployments. */
    RAILWAY_GIT_PR_NUMBER: emptyToUndefined
      .pipe(z.string().regex(/^\d+$/, "RAILWAY_GIT_PR_NUMBER must be numeric"))
      .optional(),
    /** Public domain generated by Railway for the current deployment. */
    RAILWAY_PUBLIC_DOMAIN: emptyToUndefined.optional(),
    S3_ENDPOINT: z.url(),
    S3_ACCESS_KEY: emptyToUndefined.pipe(z.string().min(1)),
    S3_SECRET_KEY: emptyToUndefined.pipe(z.string().min(1)),
    S3_BUCKET: emptyToUndefined.pipe(z.string().min(1)),
    S3_REGION: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("us-east-1"),
    /** Use path-style S3 URLs. Required for MinIO and Supabase Storage S3. */
    S3_FORCE_PATH_STYLE: z.preprocess(
      (val) =>
        typeof val === "string" && val.trim() === ""
          ? undefined
          : val === "true" || val === undefined,
      z.boolean().default(true),
    ),
    /** Supabase's S3-compatible endpoint does not support bucket-policy APIs. */
    S3_SKIP_BUCKET_POLICY: envFlag(false),
    /** IP address of the trusted reverse proxy (e.g., Render, Cloudflare). When set, X-Forwarded-For is trusted for rate limiting. */
    TRUSTED_PROXY_IP: z.string().min(1).optional(),
    /** Slug of the demo organization. When set, write operations are blocked for this org. */
    DEMO_ORG_SLUG: emptyToUndefined.optional(),
    /** Fine-grained GitHub PAT with Issues:write scope. When set (along with GITHUB_FEEDBACK_REPO), enables in-app feedback. */
    GITHUB_FEEDBACK_TOKEN: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** GitHub repo in "owner/repo" format for feedback issues. */
    GITHUB_FEEDBACK_REPO: emptyToUndefined
      .pipe(
        z.string().regex(/^[^/]+\/[^/]+$/, 'Must be in "owner/repo" format'),
      )
      .optional(),
    /** Resend API key for transactional emails (invitations, etc.). When not set, emails are logged to console. */
    RESEND_API_KEY: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Sender email address for Resend emails. Must be a verified domain in Resend. */
    RESEND_FROM_EMAIL: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("Factory Careers <careers@thefactoryhq.com>"),
    /** SMTP hostname for outbound email (e.g. smtp.gmail.com). When set, SMTP is used instead of Resend. */
    SMTP_HOST: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** SMTP port. Defaults to 587 (STARTTLS). Use 465 for implicit TLS, 25 for unencrypted. */
    SMTP_PORT: z.preprocess(
      (val) => {
        if (typeof val === 'string' && val.trim() === '') return 587
        if (val === undefined) return 587
        const n = Number(val)
        return Number.isNaN(n) ? val : n
      },
      z.number().int().min(1).max(65535).default(587),
    ),
    /** SMTP username for authentication. Omit for anonymous relay. */
    SMTP_USER: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** SMTP password for authentication. Omit for anonymous relay. */
    SMTP_PASS: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Sender address for SMTP emails. */
    SMTP_FROM: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default('Factory Careers <careers@thefactoryhq.com>'),
    /** Use implicit TLS on port 465. When false, uses STARTTLS (port 587). Defaults to false. */
    SMTP_SECURE: z.preprocess(
      (val) => typeof val === 'string' && val.trim() === '' ? false : val === 'true',
      z.boolean().default(false),
    ),
    /** Google OAuth2 Client ID for Calendar integration. Obtain from Google Cloud Console. */
    GOOGLE_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Google OAuth2 Client Secret for Calendar integration. */
    GOOGLE_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Google OAuth2 Client ID for social sign-in. Obtain from Google Cloud Console → Credentials. */
    AUTH_GOOGLE_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Google OAuth2 Client Secret for social sign-in. */
    AUTH_GOOGLE_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** GitHub OAuth App Client ID for social sign-in. Obtain from GitHub Developer Settings. */
    AUTH_GITHUB_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** GitHub OAuth App Client Secret for social sign-in. */
    AUTH_GITHUB_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Microsoft Entra ID Client ID for social sign-in. Obtain from Azure Portal → App Registrations. */
    AUTH_MICROSOFT_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Microsoft Entra ID Client Secret for social sign-in. */
    AUTH_MICROSOFT_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Microsoft Entra ID Tenant ID. Defaults to 'common' (multi-tenant). */
    AUTH_MICROSOFT_TENANT_ID: emptyToUndefined.pipe(z.string().min(1)).optional().default('common'),
    /** Shared secret for authenticating cron/scheduled job requests (e.g., webhook renewal). */
    CRON_SECRET: emptyToUndefined.pipe(z.string().min(16)).optional(),
    /** OIDC client ID for SSO authentication (e.g., Keycloak, Authentik, Authelia, Okta). */
    OIDC_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** OIDC client secret for SSO authentication. */
    OIDC_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** OIDC discovery URL (must point to a .well-known/openid-configuration endpoint). */
    OIDC_DISCOVERY_URL: emptyToUndefined.pipe(
      z.string().url().refine(
        (url) => url.startsWith('https://') || url.startsWith('http://'),
        'OIDC_DISCOVERY_URL must use HTTPS (or HTTP for local development)',
      ),
    ).optional(),
    /** Display name for the SSO button (e.g., "Company SSO", "Keycloak"). Defaults to "SSO". */
    OIDC_PROVIDER_NAME: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("SSO"),
    /** Factory-branded product name shown in fork-specific copy. */
    FACTORY_APP_NAME: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("Factory Careers"),
    /** Single bootstrapped organization name. */
    FACTORY_ORG_NAME: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("Factory"),
    /** Single bootstrapped organization slug. */
    FACTORY_ORG_SLUG: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("factory"),
    /** Comma-separated staff email domains allowed to create/sign in before invitation approval. */
    FACTORY_ALLOWED_EMAIL_DOMAINS: commaList(["thefactoryhq.com"]),
    /** Comma-separated email addresses allowed to perform emergency first-org bootstrap. */
    FACTORY_INITIAL_OWNER_EMAILS: commaList([]),
    /** Hiring team notification inbox for new public applications. */
    FACTORY_CAREERS_HIRING_INBOX: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("careers@thefactoryhq.com"),
    /** Disable public email/password account creation for staff access. */
    FACTORY_DISABLE_PUBLIC_SIGNUP: envFlag(true),
    /** Disable arbitrary organization creation; the Factory org is seeded. */
    FACTORY_DISABLE_PUBLIC_ORG_CREATION: envFlag(true),
  })
  .superRefine((data, ctx) => {
    // BETTER_AUTH_URL is explicit on Render; Railway preview compatibility is
    // retained from upstream for temporary review apps.
    if (!data.BETTER_AUTH_URL && !data.RAILWAY_PUBLIC_DOMAIN) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["BETTER_AUTH_URL"],
        message:
          "BETTER_AUTH_URL is required when RAILWAY_PUBLIC_DOMAIN is not available",
      });
    }

    // SMTP: credentials without a host is a misconfiguration.
    if (!data.SMTP_HOST && (data.SMTP_USER || data.SMTP_PASS)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['SMTP_HOST'],
        message: 'SMTP_HOST is required when SMTP_USER or SMTP_PASS is set.',
      })
    }

    // OIDC SSO requires all three vars or none — partial config is a misconfiguration.
    const oidcVars = [
      ["OIDC_CLIENT_ID", data.OIDC_CLIENT_ID],
      ["OIDC_CLIENT_SECRET", data.OIDC_CLIENT_SECRET],
      ["OIDC_DISCOVERY_URL", data.OIDC_DISCOVERY_URL],
    ] as const;
    const setVars = oidcVars.filter(([, v]) => v);
    const missingVars = oidcVars.filter(([, v]) => !v);

    if (setVars.length > 0 && missingVars.length > 0) {
      for (const [name] of missingVars) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: [name],
          message: `${name} is required when OIDC SSO is partially configured. Set all three OIDC variables (OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, OIDC_DISCOVERY_URL) or none.`,
        });
      }
    }
  });

/**
 * Validated environment variables. Uses lazy initialization so the schema
 * is only parsed on first access at runtime — not at import time. This
 * prevents build-time prerendering from failing when env vars aren't
 * available during the build phase.
 */
export const env = new Proxy({} as z.infer<typeof envSchema>, {
  get(_, prop: string | symbol) {
    // During build-time prerendering, env vars aren't available.
    // Return safe defaults so the prerenderer can boot without crashing.
    if (import.meta.prerender) {
      return "";
    }

    if (typeof prop === "symbol") return undefined;

    // Parse once on first access, then cache for all subsequent reads
    if (!(globalThis as Record<string, unknown>).__env) {
      const result = envSchema.safeParse(process.env);
      if (!result.success) {
        const missing = result.error.issues
          .map((i) => `  - ${i.path.join(".")}: ${i.message}`)
          .join("\n");
        console.error(
          `\n[Factory Careers] ❌ Missing or invalid environment variables:\n${missing}\n\n` +
            `Ensure these variables are set in the Render web service environment.\n` +
            `Required: DATABASE_URL, BETTER_AUTH_SECRET, S3_ENDPOINT, S3_ACCESS_KEY, S3_SECRET_KEY, S3_BUCKET\n` +
            `Required on Render: BETTER_AUTH_URL=https://careers.thefactoryhq.com\n` +
            `Optional: BETTER_AUTH_TRUSTED_ORIGINS, S3_REGION (default: us-east-1), S3_FORCE_PATH_STYLE (default: true), S3_SKIP_BUCKET_POLICY, TRUSTED_PROXY_IP, DEMO_ORG_SLUG, RESEND_API_KEY, RESEND_FROM_EMAIL, SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM, SMTP_SECURE, OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, OIDC_DISCOVERY_URL, OIDC_PROVIDER_NAME, AUTH_GOOGLE_CLIENT_ID, AUTH_GOOGLE_CLIENT_SECRET, AUTH_GITHUB_CLIENT_ID, AUTH_GITHUB_CLIENT_SECRET, AUTH_MICROSOFT_CLIENT_ID, AUTH_MICROSOFT_CLIENT_SECRET, AUTH_MICROSOFT_TENANT_ID, FACTORY_CAREERS_HIRING_INBOX, FACTORY_ALLOWED_EMAIL_DOMAINS, FACTORY_INITIAL_OWNER_EMAILS\n`,
        );
        throw result.error;
      }
      (globalThis as Record<string, unknown>).__env = result.data;
    }

    return (
      (globalThis as Record<string, unknown>).__env as Record<string, unknown>
    )[prop];
  },
});
