import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const readProjectFile = (path: string) =>
  readFileSync(join(process.cwd(), path), 'utf8')

describe('email workflow templates', () => {
  it('models workflow-specific templates and organization email defaults', () => {
    const schema = readProjectFile('server/database/schema/app.ts')
    const templateSchema = readProjectFile('server/utils/schemas/emailTemplate.ts')
    const orgSettingsSchema = readProjectFile('server/utils/schemas/orgSettings.ts')
    const getEndpoint = readProjectFile('server/api/org-settings/index.get.ts')
    const patchEndpoint = readProjectFile('server/api/org-settings/index.patch.ts')
    const migration = readProjectFile('server/database/migrations/0046_email_workflows.sql')
    const journal = readProjectFile('server/database/migrations/meta/_journal.json')

    expect(schema).toContain("emailTemplatePurposeEnum = pgEnum('email_template_purpose'")
    expect(schema).toContain("purpose: emailTemplatePurposeEnum('purpose').notNull().default('interview_invitation')")
    expect(schema).toContain("sendApplicationAcknowledgement: boolean('send_application_acknowledgement').notNull().default(true)")
    expect(schema).toContain("sendApplicationRejection: boolean('send_application_rejection').notNull().default(false)")
    expect(schema).toContain("applicationAcknowledgementTemplateId: text('application_acknowledgement_template_id')")
    expect(schema).toContain("applicationAcknowledgementDelayMinutes: integer('application_acknowledgement_delay_minutes').notNull().default(0)")
    expect(schema).toContain("applicationAcknowledgementBusinessHoursOnly: boolean('application_acknowledgement_business_hours_only').notNull().default(false)")
    expect(schema).toContain("applicationRejectionTemplateId: text('application_rejection_template_id')")
    expect(schema).toContain("applicationRejectionDelayMinutes: integer('application_rejection_delay_minutes').notNull().default(0)")
    expect(schema).toContain("applicationRejectionBusinessHoursOnly: boolean('application_rejection_business_hours_only').notNull().default(false)")
    expect(schema).toContain("interviewInvitationTemplateId: text('interview_invitation_template_id')")
    expect(schema).toContain("emailBusinessHoursTimezone: text('email_business_hours_timezone').notNull().default('America/New_York')")
    expect(schema).toContain("emailBusinessHoursStartHour: integer('email_business_hours_start_hour').notNull().default(9)")
    expect(schema).toContain("emailBusinessHoursEndHour: integer('email_business_hours_end_hour').notNull().default(17)")

    expect(templateSchema).toContain("EMAIL_TEMPLATE_PURPOSES = ['interview_invitation', 'application_acknowledgement', 'application_rejection']")
    expect(templateSchema).toContain('purpose: emailTemplatePurposeSchema.default(\'interview_invitation\')')
    expect(orgSettingsSchema).toContain('sendApplicationAcknowledgement: z.boolean().optional()')
    expect(orgSettingsSchema).toContain('sendApplicationRejection: z.boolean().optional()')
    expect(orgSettingsSchema).toContain('applicationAcknowledgementDelayMinutes: z.number().int().min(0).max(10080).optional()')
    expect(orgSettingsSchema).toContain('applicationRejectionDelayMinutes: z.number().int().min(0).max(10080).optional()')
    expect(orgSettingsSchema).toContain('emailBusinessHoursTimezone: z.string()')
    expect(orgSettingsSchema).toContain('Business hours end must be after start')
    expect(getEndpoint).toContain('sendApplicationAcknowledgement: settings?.sendApplicationAcknowledgement ?? true')
    expect(getEndpoint).toContain('sendApplicationRejection: settings?.sendApplicationRejection ?? false')
    expect(getEndpoint).toContain('applicationAcknowledgementBusinessHoursOnly: settings?.applicationAcknowledgementBusinessHoursOnly ?? false')
    expect(getEndpoint).toContain("emailBusinessHoursTimezone: settings?.emailBusinessHoursTimezone ?? 'America/New_York'")
    expect(patchEndpoint).toContain('sendApplicationAcknowledgement: body.sendApplicationAcknowledgement ?? true')
    expect(patchEndpoint).toContain('applicationRejectionDelayMinutes: body.applicationRejectionDelayMinutes ?? 0')
    expect(patchEndpoint).toContain('emailBusinessHoursEndHour: body.emailBusinessHoursEndHour ?? 17')

    expect(migration).toContain('CREATE TYPE "public"."email_template_purpose"')
    expect(migration).toContain('ALTER TABLE "email_template" ADD COLUMN IF NOT EXISTS "purpose"')
    expect(migration).toContain('ALTER TABLE "org_settings" ADD COLUMN IF NOT EXISTS "send_application_acknowledgement"')
    expect(migration).toContain('ALTER TABLE "org_settings" ADD COLUMN IF NOT EXISTS "application_rejection_business_hours_only"')
    expect(migration).toContain('ALTER TABLE "org_settings" ADD COLUMN IF NOT EXISTS "email_business_hours_timezone"')
    expect(journal).toContain('"tag": "0046_email_workflows"')
  })

  it('exposes email templates as a top-level Emails destination with compatibility redirects', () => {
    const topBar = readProjectFile('app/components/AppTopBar.vue')
    const emailsWorkflow = readProjectFile('app/pages/dashboard/emails/index.vue')
    const emailsIndex = readProjectFile('app/pages/dashboard/emails/templates/index.vue')
    const sectionTabs = readProjectFile('app/components/EmailSectionTabs.vue')
    const workflowSettings = readProjectFile('app/components/EmailWorkflowSettings.vue')
    const oldIndex = readProjectFile('app/pages/dashboard/interviews/templates/index.vue')
    const oldNew = readProjectFile('app/pages/dashboard/interviews/templates/new.vue')
    const oldDetail = readProjectFile('app/pages/dashboard/interviews/templates/[id].vue')

    expect(topBar).toContain("{ label: 'Emails', to: '/dashboard/emails'")
    expect(topBar).toContain("'Emails'")
    expect(emailsWorkflow).toContain('Email Workflows')
    expect(emailsWorkflow).toContain('<EmailWorkflowSettings />')
    expect(sectionTabs).toContain("to: '/dashboard/emails'")
    expect(sectionTabs).toContain("to: '/dashboard/emails/templates'")
    expect(emailsIndex).toContain('Built-in Templates')
    expect(workflowSettings).toContain('Workflow Settings')
    expect(workflowSettings).toContain('sendApplicationAcknowledgement')
    expect(workflowSettings).toContain('sendApplicationRejection')
    expect(workflowSettings).toContain('workflowDelayOptions')
    expect(workflowSettings).toContain('Business hours only')
    expect(workflowSettings).toContain('businessHourTimezoneOptions')
    expect(workflowSettings).toContain('emailBusinessHoursStartHour')
    expect(workflowSettings).toContain('application_acknowledgement')
    expect(workflowSettings).toContain('application_rejection')
    expect(oldIndex).toContain("navigateTo(localePath('/dashboard/emails/templates'), { replace: true })")
    expect(oldNew).toContain("navigateTo(localePath('/dashboard/emails/templates/new'), { replace: true })")
    expect(oldDetail).toContain("navigateTo(localePath(`/dashboard/emails/templates/${route.params.id}`), { replace: true })")
  })

  it('links application and rejection sends to configured workflow templates', () => {
    const publicApply = readProjectFile('server/api/public/jobs/[slug]/apply.post.ts')
    const applicationPatch = readProjectFile('server/api/applications/[id].patch.ts')
    const emailUtils = readProjectFile('server/utils/email.ts')
    const systemTemplates = readProjectFile('shared/system-templates.ts')

    expect(publicApply).toContain('sendConfiguredApplicationAcknowledgementEmail')
    expect(publicApply).not.toContain('sendApplicationTeamAlertEmail')
    expect(publicApply).toContain('database trigger')
    expect(applicationPatch).toContain('sendConfiguredApplicationRejectionEmail')
    expect(applicationPatch).toContain("body.status === 'rejected'")
    expect(emailUtils).toContain('renderCandidateWorkflowTemplate')
    expect(emailUtils).toContain('sendApplicationRejectionEmail')
    expect(emailUtils).toContain('sendCandidateWorkflowEmailWithTiming')
    expect(emailUtils).toContain('nextBusinessSendTime')
    expect(emailUtils).toContain('getZonedDateParts')
    expect(emailUtils).toContain('businessHoursTimezone')
    expect(systemTemplates).toContain("purpose: 'application_acknowledgement'")
    expect(systemTemplates).toContain("purpose: 'application_rejection'")
  })
})
